ENTERPRISE_MOD_DIR := $(USERMOD_DIR)

SRC_USERMOD += $(ENTERPRISE_MOD_DIR)/enterprise.c

CFLAGS_USERMOD += -I$(ENTERPRISE_MOD_DIR)

CFLAGS_USERMOD += -DMICROPY_PY_ENTERPRISE=1
CFLAGS_USERMOD += -DMICROPY_PY_ENTERPRISE_NUMBER=1
CFLAGS_USERMOD += -DMICROPY_PY_ENTERPRISE_PUBLIC_KEY=1
